### ISSUE TITLE
About Adain code

### ISSUE THREAD

**Issue by ghost** [wangkaihong/BiSIDA#1]
Hi, kaihong, Thanks for your code! It's an amazing work.
But I have some problems about your code.
In adain/train_0_1.py, does it mean to change the 'content_images' and 'style_images' randomly at each iteration?
`if np.random.rand() > 0.5:
            content_images = source_image
            style_images = target_image_full.squeeze()
        else:
            content_images = target_image
            style_images = source_image_full.squeeze()
        content_images = content_images.to(device).float() `

**Comment by wangkaihong** [comment]
Hi, thanks for your interest in our work!

Having content and source images switching randomly means when we train the Adain generator, we not only train it to perform style transfer from the source domain (Synthetic) to the target domain (CityScapes) but also from the opposite direction.

**Comment by ghost** [comment]
Thanks for your reply! I notice that when training the self-ensembling framework, the style transferring on source_image and target_image also happens randomly. I want to know the meaning of it. Can it improve the robustness of models?
`source_transfer = np.random.rand() > (1 - self.src_transfer_rate)
  target_transfer = np.random.rand() > (1 - self.tgt_transfer_rate)`

**Comment by wangkaihong** [comment]
We bypass the transfer process in certain probabilities just so the model could be trained on the original image without loss of resolution and yes, it could also enhance the robustness of the model.

We just have our latest version paper released, you may find more details here: 
https://ojs.aaai.org/index.php/AAAI/article/view/17216

**Comment by ghost** [comment]
Thanks for your help~~
